import { Inter } from "next/font/google";
import "./globals.css";
import FooterPage from "./components/footer/FooterPage.jsx";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="Container">
        <Navbar/>

        {children}
     
  <FooterPage/>
        </div>
        </body>
    </html>
  );
}
